[buildPlans.Js]
family = "JS"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Js.variants]
  inherits = "ss06"

    [buildPlans.Js.variants.design]
    two = "straight-neck-serifless"
    six = "straight-bar"
    nine = "straight-bar"
    capital-g = "toothed-serifless-hookless"
    capital-q = "crossing"
    tittle = "round"
    diacritic-dot = "round"
    punctuation-dot = "round"
    ampersand = "closed"
    at = "compact"
    lig-ltgteq = "slanted"

  [buildPlans.Js.ligations]
  inherits = "javascript"

[buildPlans.Js.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Js.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Js.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Js.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Js.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Js.widths.Normal]
shape = 500
menu = 5
css = "normal"