[buildPlans.Ts]
family = "TS"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Ts.variants]
  inherits = "ss06"

    [buildPlans.Ts.variants.design]
    two = "straight-neck-serifless"
    six = "straight-bar"
    nine = "straight-bar"
    zero = "long-dotted"
    capital-g = "toothed-serifless-hookless"
    capital-q = "crossing"
    tittle = "round"
    diacritic-dot = "round"
    punctuation-dot = "round"
    at = "compact"
    lig-ltgteq = "slanted"

  [buildPlans.Ts.ligations]
  inherits = "javascript"

[buildPlans.Ts.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Ts.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Ts.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Ts.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Ts.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Ts.widths.Normal]
shape = 500
menu = 5
css = "normal"

# sudo apt install ttfautohint
# npm install
# npm run build -- contents::Ts
