[buildPlans.Ts]
family = "TS"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Ts.variants]
  inherits = "ss05"

    [buildPlans.Ts.variants.design]
    six = "straight-bar"
    nine = "straight-bar"
    zero = "dotted"
    capital-g = "toothed-serifless-hookless"
    capital-m = "hanging-serifless"
    capital-q = "crossing"
    f = "flat-hook-serifless"
    g = "single-storey-serifless"
    r = "hookless-serifless"
    ampersand = "closed"

  [buildPlans.Ts.ligations]
  inherits = "javascript"

[buildPlans.Ts.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Ts.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Ts.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Ts.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Ts.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Ts.widths.Normal]
shape = 500
menu = 5
css = "normal"