.PHONY: create install format

create:
	npm create vue@latest # deprecated
	yarn create vue # deprecated
	pnpm create vue

install:
	pnpm install -g ts-node @types/node
	pnpm install sass
	pnpm install element-plus
	pnpm install -D unplugin-vue-components unplugin-auto-import
	pnpm install @element-plus/icons-vue
	pnpm install axios