.PHONY: create install

create:
	npm create vue@latest
	yarn create vue
	pnpm create vue

install:
	npm install -g ts-node @types/node
	npm install sass
	npm install element-plus
	npm install -D unplugin-vue-components unplugin-auto-import
