[buildPlans.Harmony]
family = "Harmony"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Harmony.variants]
  inherits = "ss06" # Liberation Mono

    [buildPlans.Harmony.variants.design]
    two = "straight-neck-serifless" # 2
    six = "straight-bar" # 6
    seven = "straight-serifless" # 7
    nine = "straight-bar" # 9
    capital-g = "toothed-serifless-hookless" # G
    capital-j = "serifless" # J
    capital-q = "crossing" # Q
    i = "serifed-flat-tailed" # i
    j = "serifless" # j
    tittle = "round"
    diacritic-dot = "round"
    punctuation-dot = "round"
    at = "compact" # @
    lig-ltgteq = "slanted" # <=

  [buildPlans.Harmony.ligations]
  inherits = "javascript"

[buildPlans.Harmony.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Harmony.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Harmony.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Harmony.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Harmony.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Harmony.widths.Normal]
shape = 500
menu = 5
css = "normal"